// @ts-nocheck
import typescript from "@typescript-eslint/eslint-plugin";
import playwright from "eslint-plugin-playwright";
import typescriptParser from "@typescript-eslint/parser";

const { configs: typescriptConfigs } = typescript;

export default [
  {
    files: ["**/*.ts", "**/*.tsx", "**/*.js"],
    plugins: {
      "@typescript-eslint": typescript,
      playwright: playwright,
    },
    languageOptions: {
      parser: typescriptParser,
      parserOptions: {
        ecmaVersion: "latest",
        sourceType: "module",
      },
    },
    rules: {
      ...typescriptConfigs.recommended.rules,
      ...playwright.configs["flat/recommended"].rules,
      "no-console": 0,
      "constructor-super": "error",
      "for-direction": "error",
      "getter-return": "error",
      "no-async-promise-executor": "error",
      "no-case-declarations": "error",
      "no-class-assign": "error",
      "no-compare-neg-zero": "error",
      "no-cond-assign": "error",
      "no-const-assign": "error",
      "no-control-regex": "error",
      "no-debugger": "error",
      "no-delete-var": "error",
      "no-dupe-args": "error",
      "no-dupe-class-members": "error",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-duplicate-imports": "error",
      "no-empty": "error",
      "no-empty-pattern": "error",
      "no-extra-boolean-cast": "error",
      "no-extra-semi": "error",
      "no-fallthrough": "error",
      "no-func-assign": "error",
      "no-global-assign": "error",
      "no-invalid-regexp": "error",
      "no-irregular-whitespace": "error",
      "no-misleading-character-class": "error",
      "no-mixed-spaces-and-tabs": "error",
      "no-new-symbol": "error",
      "no-obj-calls": "error",
      "no-octal": "error",
      "no-prototype-builtins": "error",
      "no-redeclare": "error",
      "no-regex-spaces": "error",
      "no-self-assign": "error",
      "no-self-compare": "error",
      "no-setter-return": "error",
      "no-template-curly-in-string": "error",
      "no-shadow-restricted-names": "error",
      "no-sparse-arrays": "error",
      "no-this-before-super": "error",
      "no-undef": "off",
      "no-unreachable": "error",
      "no-unreachable-loop": "error",
      "no-unsafe-finally": "error",
      "no-unsafe-negation": "error",
      "no-unsafe-optional-chaining": "error",
      "no-unused-labels": "error",
      "no-useless-catch": "error",
      "no-useless-escape": "error",
      "no-with": "error",
      "require-atomic-updates": "error",
      "require-yield": "error",
      "use-isnan": "error",
      "valid-typeof": "error",
      "comma-style": "error",
      "computed-property-spacing": "error",
      "default-param-last": "error",
      "dot-notation": 0,
      "func-names": "error",
      "guard-for-in": "error",
      "linebreak-style": 0,
      "max-params": ["error", 14],
      "newline-before-return": "error",
      "no-empty-function": "warn",
      "no-trailing-spaces": "error",
      "no-use-before-define": "error",
      "no-useless-concat": "error",
      "no-useless-rename": "error",
      "no-useless-return": "error",
      "no-unused-vars": "warn",
      "no-var": "error",
      "no-dupe-else-if": "error",
      "no-continue": "error",
      "prefer-const": "error",
      "prefer-arrow-callback": "error",
      "prefer-destructuring": 0,
      "playwright/expect-expect": 0,

      quotes: [
        "error",
        "single",
        {
          avoidEscape: true,
        },
      ],

      "rest-spread-spacing": "error",

      "object-curly-spacing": [
        "error",
        "always",
        {
          objectsInObjects: true,
        },
      ],

      "arrow-spacing": "error",
      "block-spacing": "error",
      "semi-spacing": "error",
      "key-spacing": "error",
      "comma-spacing": "error",
      "keyword-spacing": "error",
      semi: "off",
      "vars-on-top": "error",
      "comma-dangle": ["error", "never"],
      "array-callback-return": 0,
      "no-await-in-loop": "error",
      "no-constant-binary-expression": "error",
      "no-constant-condition": "error",
      "no-constructor-return": "error",
      "no-empty-character-class": "error",
      "no-ex-assign": "error",
      "no-import-assign": "error",
      "no-inner-declarations": "error",
      "no-loss-of-precision": "error",
      "no-new-native-nonconstructor": "error",
      "no-unexpected-multiline": "error",
      "no-unmodified-loop-condition": "error",
      "no-unused-private-class-members": "error",
      "no-useless-assignment": 0,
      "no-useless-backreference": "error",
      camelcase: 0,
      "capitalized-comments": 0,
      "consistent-return": 0,
      "default-case": "warn",
      "func-name-matching": "error",
      "init-declarations": 0,
      "no-else-return": "error",
      "no-empty-static-block": "error",
      "no-eq-null": "error",
      "no-eval": "error",
      "no-extend-native": "error",
      "no-extra-bind": "error",
      "no-extra-label": "error",
      "no-implicit-coercion": "error",
      "no-implicit-globals": "error",
      "no-implied-eval": "error",
      "no-invalid-this": 0,
      "no-iterator": "error",
      "no-label-var": "error",
      "no-labels": "error",
      "no-lone-blocks": "error",
      "no-lonely-if": "error",
      "no-loop-func": "error",
      "no-magic-numbers": 0,
      "no-multi-assign": "error",
      "no-multi-str": "error",
      "no-negated-condition": 0,
      "no-nested-ternary": "error",
      "no-new": "error",
      "no-new-wrappers": "error",
      "no-nonoctal-decimal-escape": "error",
      "no-object-constructor": "error",
      "no-octal-escape": "error",
      "no-param-reassign": "error",
      "no-proto": "error",
      "no-restricted-exports": "error",
      "no-restricted-globals": "error",
      "no-restricted-imports": "error",
      "no-restricted-properties": "error",
      "no-restricted-syntax": "error",
      "no-return-assign": "error",
      "no-script-url": "error",
      "no-sequences": "error",
      "no-shadow": "error",
      "no-throw-literal": "error",
      "no-undef-init": "error",
      "no-undefined": "error",
      "no-underscore-dangle": "error",
      "no-unneeded-ternary": "error",
      "no-unused-expressions": 0,
      "no-useless-call": "error",
      "no-useless-computed-key": "error",
      "no-useless-constructor": "error",
      "no-void": "error",
      "no-warning-comments": "error",
      "one-var": 0,
      "operator-assignment": 0,
      "prefer-exponentiation-operator": "error",
      "prefer-named-capture-group": 0,
      "prefer-numeric-literals": "error",
      "prefer-object-has-own": "error",
      "prefer-object-spread": "error",
      "prefer-promise-reject-errors": "error",
      "prefer-rest-params": "error",
      "prefer-spread": "error",
      "prefer-template": 0,
      radix: 0,
      "require-await": 0,
      strict: "error",
      "symbol-description": "error",
      yoda: "error",
    },
  },
];
